# Generated by Django 3.1.4 on 2021-02-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_orders_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Indo', 'Indoor'), ('Outdo', 'Outdoor')], max_length=100, null=True),
        ),
    ]
