# Generated by Django 3.1.4 on 2021-02-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210204_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Indo', 'Indoo'), ('Outdo', 'Outdoo')], max_length=100, null=True),
        ),
    ]
